baseURL = "https://yanxiaochuan.github.io/"
defaultContentLanguage = "en"
enableRobotsTXT = true
theme = "blowfish"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[article]
  showDate = true
  showReadingTime = false
  showSummary = true
  showTags = false
  showTableOfContents = false
  showBreadcrumbs = false
  showComments = true
