colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showThemeAttribution = false
  showCopyright = true
  showScrollToTop = true
  showAppearanceSwitcher = false

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showReadingTime = false
  showWordCount = false
  showSummary = false
  showTaxonomies = false
  showTags = false
  showTableOfContents = true
  showBreadcrumbs = false
  showComments = true
  showPagination = false
  showHeadingAnchors = true
  sharingLinks = false

[list]
  groupByYear = false
  showCards = false
  cardView = false
  showSummary = false
